### ISSUE TITLE
Define shaders outside of CoffeeScript.

### ISSUE THREAD

**Issue by vorporeal** [adam-zethraeus/xylem.js#11]
By inlining the shaders in a .coffee file, it necessitates the rebuilding of Xylem.js whenever the shader source is changed.  This adds a lot of unnecessary overhead to the process of iterating on shader implementations (not only do you need to rebuild Xylem.js, but you need to have `coffee` and `cake` installed).

**Comment by adam-zethraeus** [comment]
Yeah. requesting them with the resource loader was yucky when they really didn't conceptually belong in a map file - but I agree with you. I guess I'll end up putting them in script tags.

**Comment by adam-zethraeus** [comment]
/ feel free to submit a pull request w/ an implementation. I can get around to it soon, otherwise.

**Comment by adam-zethraeus** [comment]
done.

**Comment by adam-zethraeus** [comment]
i am going to want to package it as a nice and usable .js at some point, and i'll have to start compiling in default shaders then - but that's a significant way off :)
