### ISSUE TITLE
Resources should have explicit types.

### ISSUE THREAD

**Issue by adam-zethraeus** [adam-zethraeus/xylem.js#4]
Resources should be imported into holder objects signifying type.

**Comment by vorporeal** [comment]
The first question that came to mind when I saw this was: Should xylem even handle resource loading?  More generally, what is xylem's scope?  If it's purpose is solely to be a renderer that can nicely integrate with other systems, those systems should be responsible for resource loading.

**Comment by adam-zethraeus** [comment]
Agreed that there's a fair amount of cruft associated with it in the context of acorn. We should talk about that AFK.
