### ISSUE TITLE
[Feature Request] Framebuffer manager

### ISSUE THREAD

**Issue by vorporeal** [adam-zethraeus/xylem.js#6]
Looking at [[commit 6bdc0]](https://github.com/zethraeus/xylem/commit/6bdc0ac1b28ca50ccb13f70658f68eb9927d244d), it seems like Texture.drawTo creates a new framebuffer for each call and never deletes it.  This is an inefficient use of both processor cycles and memory.

I propose the creation of a framebuffer manager which can be used to create, distribute, and clean up temporary (and named?) framebuffers.

Pseudocode of my thoughts:

``` javascript
// NOTE: This doesn't support framebuffers of different sizes, but
//       that is easy to add.

/** @returns {WebGLFramebuffer} */
function getTempFramebuffer() {
  if (framebufferPool.empty()) {
    this.createNewTempFramebuffer();
  }
  return framebufferPool.get(0);
}

/** @param {WebGLFramebuffer} fb */
function returnTempFramebuffer(fb) {
  if (framebufferPool.indexOf(fb) != -1) {
    framebufferPool.push(fb);
  }
}
```

**Comment by adam-zethraeus** [comment]
Cool. I'll look into it. I'm still not set on having the FBO stuff as a shim in Texture in general

**Comment by adam-zethraeus** [comment]
as far as deletion: everything [citation needed] in webgl is deleted as though with it's corresponding gles glDeleteXXX call when JS garbage collection comes around. (1,2)

I've modified Texture such that the framebuffer and renderbuffers are lazily initialised on drawTo and stick around as members. I think this ignoring of framebuffer/renderbuffer on the conceptual level and just having a texture you can draw to is appropriate given webgl's single render target limitation.

What do you think?
1. http://www.khronos.org/message_boards/viewtopic.php?f=35&t=3637 
2. https://www.khronos.org/registry/webgl/specs/1.0/#5.5
