### ISSUE TITLE
Render to texture of size 1024*1024 silently fails.

### ISSUE THREAD

**Issue by adam-zethraeus** [adam-zethraeus/xylem.js#7]
512*512 works. Weirdness.

**Comment by vorporeal** [comment]
Reproducible with which browsers? Does the WebGL spec define a maximum
render target size?

**Comment by adam-zethraeus** [comment]
It could very well be a limitation on my local machine or something stupid. I haven't taken the time to investigate further since working out what was causing the rendering to black screen.

**Comment by adam-zethraeus** [comment]
repros in firefox btw. Will try on another machine tomorrow.

**Comment by adam-zethraeus** [comment]
happens on different machines too.

Puzzling.

**Comment by vorporeal** [comment]
A quick Google indicates that it should work for at least 1024x1024.  If
you tell me how to run the test, I can see how a couple of my machines
handle it.

**Comment by adam-zethraeus** [comment]
well, I uploaded a build to http://zethrae.us/lol and you can change line 115 of Xylem.js - but I'm now pretty sure it's not a machine thing. 

I'm going to do some tests with changing mipmapping settings and viewport size.

**Comment by adam-zethraeus** [comment]
Disabling Mipmapping stopped the issue. Time to dive into understanding texParameteri settings.
Do you have any thoughts on what might have happened?

**Comment by vorporeal** [comment]
No clue.  Maybe try changing the texture wrapping from REPEAT to
CLAMP_TO_EDGE?

**Comment by adam-zethraeus** [comment]
i'm happy leaving mipmapping turned on only for the textures from images for now. I wont need it for blitting to the screen.

**Comment by vorporeal** [comment]
Thinking about it, mipmapping doesn't make sense for deferred rendering.  All of the reads from it should be at the highest LOD, so mipmaps only waste memory.

**Comment by adam-zethraeus** [comment]
it would be useful if doing portals or something, but yeah.
